apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: amberapp-controller-manager
  name: amberapp-controller-manager
  namespace: amberapp-system
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: amberapp-controller-manager
  template:
    metadata:
      labels:
        control-plane: amberapp-controller-manager
    spec:
      containers:
      - args:
        - -zap-devel=false
        - -zap-encoder=console
        - -zap-log-level=debug
        command:
        - /manager
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: registry.cn-shanghai.aliyuncs.com/jibudata/amberapp:0.0.5
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: amberapp-controller-manager
      terminationGracePeriodSeconds: 10
