apiVersion: storage.jibudata.com/v1alpha1
kind: AppHook
metadata:
  name: apphook-sample
  namespace: app-hook-operator-system
spec:
  name: apphook-sample
  appProvider: postgres
  endPoint: "postgres.postgres-ns"
  databases:
    - postgresdb
  secret: 
    name: "apphook-sample-secret"
    namespace: "app-hook-operator-system"
