//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppHook) DeepCopyInto(out *AppHook) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppHook.
func (in *AppHook) DeepCopy() *AppHook {
	if in == nil {
		return nil
	}
	out := new(AppHook)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppHook) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppHookList) DeepCopyInto(out *AppHookList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppHook, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppHookList.
func (in *AppHookList) DeepCopy() *AppHookList {
	if in == nil {
		return nil
	}
	out := new(AppHookList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppHookList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppHookSpec) DeepCopyInto(out *AppHookSpec) {
	*out = *in
	if in.Databases != nil {
		in, out := &in.Databases, &out.Databases
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TimeoutSeconds != nil {
		in, out := &in.TimeoutSeconds, &out.TimeoutSeconds
		*out = new(int32)
		**out = **in
	}
	out.Secret = in.Secret
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppHookSpec.
func (in *AppHookSpec) DeepCopy() *AppHookSpec {
	if in == nil {
		return nil
	}
	out := new(AppHookSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppHookStatus) DeepCopyInto(out *AppHookStatus) {
	*out = *in
	if in.QuiescedTimestamp != nil {
		in, out := &in.QuiescedTimestamp, &out.QuiescedTimestamp
		*out = (*in).DeepCopy()
	}
	if in.Result != nil {
		in, out := &in.Result, &out.Result
		*out = new(QuiesceResult)
		(*in).DeepCopyInto(*out)
	}
	if in.PreservedConfig != nil {
		in, out := &in.PreservedConfig, &out.PreservedConfig
		*out = new(PreservedConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppHookStatus.
func (in *AppHookStatus) DeepCopy() *AppHookStatus {
	if in == nil {
		return nil
	}
	out := new(AppHookStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MongoResult) DeepCopyInto(out *MongoResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MongoResult.
func (in *MongoResult) DeepCopy() *MongoResult {
	if in == nil {
		return nil
	}
	out := new(MongoResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MysqlResult) DeepCopyInto(out *MysqlResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MysqlResult.
func (in *MysqlResult) DeepCopy() *MysqlResult {
	if in == nil {
		return nil
	}
	out := new(MysqlResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PgResult) DeepCopyInto(out *PgResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PgResult.
func (in *PgResult) DeepCopy() *PgResult {
	if in == nil {
		return nil
	}
	out := new(PgResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PreservedConfig) DeepCopyInto(out *PreservedConfig) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PreservedConfig.
func (in *PreservedConfig) DeepCopy() *PreservedConfig {
	if in == nil {
		return nil
	}
	out := new(PreservedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuiesceResult) DeepCopyInto(out *QuiesceResult) {
	*out = *in
	if in.Mongo != nil {
		in, out := &in.Mongo, &out.Mongo
		*out = new(MongoResult)
		**out = **in
	}
	if in.Mysql != nil {
		in, out := &in.Mysql, &out.Mysql
		*out = new(MysqlResult)
		**out = **in
	}
	if in.Pg != nil {
		in, out := &in.Pg, &out.Pg
		*out = new(PgResult)
		**out = **in
	}
	if in.Redis != nil {
		in, out := &in.Redis, &out.Redis
		*out = new(RedisResult)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuiesceResult.
func (in *QuiesceResult) DeepCopy() *QuiesceResult {
	if in == nil {
		return nil
	}
	out := new(QuiesceResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedisResult) DeepCopyInto(out *RedisResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedisResult.
func (in *RedisResult) DeepCopy() *RedisResult {
	if in == nil {
		return nil
	}
	out := new(RedisResult)
	in.DeepCopyInto(out)
	return out
}
