apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: app-hook-operator-system
type: Opaque
stringData:
  username: root
  password: password
---
apiVersion: storage.jibudata.com/v1alpha1
kind: AppHook
metadata:
  name: mysql-sample
  namespace: app-hook-operator-system
spec:
  name: mysql-sample
  appProvider: mysql
  endPoint: "mysql.mysql-ns"
  databases:
    - test
  secret: 
    name: "mysql-secret"
    namespace: "app-hook-operator-system"
