apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app-hook-operator-system
type: Opaque
stringData:
  username: postgresadmin
  password: Test1234
---
apiVersion: storage.jibudata.com/v1alpha1
kind: AppHook
metadata:
  name: postgres-sample
  namespace: app-hook-operator-system
spec:
  name: postgres-sample
  appProvider: postgres
  endPoint: "postgres.postgres-ns"
  databases:
    - postgresdb
  secret: 
    name: "postgres-secret"
    namespace: "app-hook-operator-system"
