name: Build Images
on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'tag'
        required: true
        default: 'main-latest'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Alicloud Docker registry
      if: inputs.registry == 'registry.cn-shanghai.aliyuncs.com'
      uses: docker/login-action@v2
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.ALI_REGISTRY_USER }}
        password: ${{ secrets.ALI_REGISTRY_PASS }}
    - name: Build and push Docker images
      run: |
        GOPROXY=https://proxy.golang.org,direct  make docker-pushx -e VERSION=${VERSION}
      env:
        VERSION: ${{ inputs.version }}
